#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Calculator.Resource", IsApplication=true)]

namespace Calculator
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f040000
			public const int button_height = 2130968576;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f060016
			public const int ActionBackspace = 2131099670;
			
			// aapt resource value: 0x7f060014
			public const int ActionClear = 2131099668;
			
			// aapt resource value: 0x7f06001e
			public const int ActionDiv = 2131099678;
			
			// aapt resource value: 0x7f06001a
			public const int ActionMinus = 2131099674;
			
			// aapt resource value: 0x7f06001c
			public const int ActionMul = 2131099676;
			
			// aapt resource value: 0x7f060018
			public const int ActionPlus = 2131099672;
			
			// aapt resource value: 0x7f060012
			public const int ActionResult = 2131099666;
			
			// aapt resource value: 0x7f060010
			public const int Dot = 2131099664;
			
			// aapt resource value: 0x7f060011
			public const int Number0 = 2131099665;
			
			// aapt resource value: 0x7f060004
			public const int Number1 = 2131099652;
			
			// aapt resource value: 0x7f060005
			public const int Number2 = 2131099653;
			
			// aapt resource value: 0x7f060006
			public const int Number3 = 2131099654;
			
			// aapt resource value: 0x7f060008
			public const int Number4 = 2131099656;
			
			// aapt resource value: 0x7f060009
			public const int Number5 = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int Number6 = 2131099658;
			
			// aapt resource value: 0x7f06000c
			public const int Number7 = 2131099660;
			
			// aapt resource value: 0x7f06000d
			public const int Number8 = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int Number9 = 2131099662;
			
			// aapt resource value: 0x7f060002
			public const int Row0 = 2131099650;
			
			// aapt resource value: 0x7f060003
			public const int Row1 = 2131099651;
			
			// aapt resource value: 0x7f060015
			public const int Row10 = 2131099669;
			
			// aapt resource value: 0x7f060007
			public const int Row2 = 2131099655;
			
			// aapt resource value: 0x7f06000b
			public const int Row3 = 2131099659;
			
			// aapt resource value: 0x7f06000f
			public const int Row4 = 2131099663;
			
			// aapt resource value: 0x7f060013
			public const int Row5 = 2131099667;
			
			// aapt resource value: 0x7f060017
			public const int Row6 = 2131099671;
			
			// aapt resource value: 0x7f060019
			public const int Row7 = 2131099673;
			
			// aapt resource value: 0x7f06001b
			public const int Row8 = 2131099675;
			
			// aapt resource value: 0x7f06001d
			public const int Row9 = 2131099677;
			
			// aapt resource value: 0x7f060000
			public const int digits = 2131099648;
			
			// aapt resource value: 0x7f06001f
			public const int linearLayout1 = 2131099679;
			
			// aapt resource value: 0x7f060001
			public const int tableLayout1 = 2131099649;
			
			// aapt resource value: 0x7f060020
			public const int tableLayout2 = 2131099680;
			
			// aapt resource value: 0x7f060021
			public const int tableLayout3 = 2131099681;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int app_name = 2131034113;
			
			// aapt resource value: 0x7f050002
			public const int button_one_text = 2131034114;
			
			// aapt resource value: 0x7f050000
			public const int hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
